github: [Vaporjawn, Vapor-jawn, Vaporjawn-Mods]
custom: ['https://www.venmo.com/Vaporjawn', 'https://www.paypal.me/Vaporjawn', 'https://cash.app/$vaporjawn']
ko_fi: vaporjawn
patreon: u=64402381
issuehunt: vaporjawn
